openapi: 3.1.0
info:
  title: Insurance Carrier API
  description: API for insurance carriers to handle BD change validation requests and notifications in the BD change process
  version: 1.0.0
  contact:
    name: Insurance Carrier API Team
    email: api-support@example.com
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://api-staging.example.com/v1
    description: Staging server

paths:
  /receive-bd-change-request:
    post:
      summary: Receive BD change validation request from clearinghouse
      description: Accept BD change validation request from clearinghouse to validate and approve/reject broker-dealer changes
      operationId: receiveBdChangeRequest
      parameters:
        - name: transactionId
          in: header
          required: true
          description: Unique transaction identifier that flows through all related requests
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BdChangeRequest'
      responses:
        '200':
          description: BD change request received successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardResponse'
        '400':
          description: Bad request - invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /receive-transfer-notification:
    post:
      summary: Receive transfer notification from clearinghouse
      description: Accept final service agent change notification from clearinghouse
      operationId: receiveTransferNotification
      parameters:
        - name: transactionId
          in: header
          required: true
          description: Unique transaction identifier that flows through all related requests
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferNotification'
      responses:
        '200':
          description: Transfer notification received successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardResponse'
        '400':
          description: Bad request - invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /query-status/{transactionId}:
    get:
      summary: Query transaction status
      description: Retrieve current status and history for a specific transaction
      operationId: queryTransactionStatus
      parameters:
        - name: transactionId
          in: path
          required: true
          description: Unique transaction identifier
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Transaction status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionStatus'
        '404':
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    BdChangeRequest:
      type: object
      required:
        - receivingBrokerId
        - deliveringBrokerId
        - carrierId
        - policyNumber
      properties:
        receivingBrokerId:
          type: string
          description: Identifier of the receiving broker-dealer
        deliveringBrokerId:
          type: string
          description: Identifier of the delivering broker-dealer
        carrierId:
          type: string
          description: Identifier of the insurance carrier
        policyNumber:
          type: string
          description: Policy identifier
        policyDetails:
          type: object
          description: Detailed policy information for validation
        brokerDetails:
          type: object
          description: Receiving broker information for validation
        validationRequirements:
          type: object
          description: Specific validation requirements (licensing, appointments, suitability, etc.)
        requestTimestamp:
          type: string
          format: date-time
          description: When the request was made
        additionalData:
          type: object
          description: Additional request data (open-ended)

    TransferNotification:
      type: object
      required:
        - notificationType
        - policyNumber
        - carrierId
      properties:
        notificationType:
          type: string
          enum: [service-agent-change-complete]
          description: Type of transfer notification
        policyNumber:
          type: string
          description: Policy identifier
        carrierId:
          type: string
          description: Identifier of the insurance carrier
        receivingBrokerId:
          type: string
          description: Identifier of the new receiving broker-dealer
        deliveringBrokerId:
          type: string
          description: Identifier of the previous delivering broker-dealer
        effectiveDate:
          type: string
          format: date
          description: Effective date of the broker change
        notificationTimestamp:
          type: string
          format: date-time
          description: When the notification was sent
        additionalData:
          type: object
          description: Additional notification data (open-ended)

    TransactionStatus:
      type: object
      required:
        - currentStatus
        - createdAt
        - updatedAt
      properties:
        currentStatus:
          type: string
          enum: 
            - MANIFEST_REQUESTED
            - MANIFEST_RECEIVED
            - DUE_DILIGENCE_COMPLETE
            - CARRIER_VALIDATION_PENDING
            - CARRIER_APPROVED
            - CARRIER_REJECTED
            - TRANSFER_INITIATED
            - TRANSFER_PROCESSING
            - TRANSFER_CONFIRMED
            - COMPLETE
          description: Current transaction status
        statusHistory:
          type: array
          items:
            $ref: '#/components/schemas/StatusHistoryItem'
          description: History of status changes
        createdAt:
          type: string
          format: date-time
          description: Transaction creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
        brokerRole:
          type: string
          enum: [receiving, delivering]
          description: Role of this broker in the transaction (broker-dealer context)
        carrierValidationDetails:
          type: object
          description: Details about carrier validation process (insurance carrier context)
        policiesAffected:
          type: array
          items:
            type: string
          description: List of policy IDs affected in this transaction (insurance carrier context)
        additionalData:
          type: object
          description: Additional status data (open-ended)

    StatusHistoryItem:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          description: Status value
        timestamp:
          type: string
          format: date-time
          description: When status was set
        notes:
          type: string
          description: Additional notes about status change

    StandardResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Response code indicating the result status
          example: "RECEIVED"
        message:
          type: string
          description: Human-readable response message describing the operation result
        processingStatus:
          type: string
          enum: [received, processing, deferred]
          description: How the request will be handled
        estimatedResponseTime:
          type: string
          description: Estimated time for validation response (if deferred)

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
          example: "VALIDATION_ERROR"
        message:
          type: string
          description: Human-readable error message

  # Note: Outbound API calls that carriers make to clearinghouse are documented separately
  # These would include:
  # - POST to clearinghouse /receive-carrier-response (validation response with approval/rejection)
  #
  # Example carrier validation response payload that would be sent to clearinghouse:
  # {
  #   "transactionId": "uuid",
  #   "carrierId": "string",  
  #   "policyId": "string",
  #   "validationResult": "approved|rejected",
  #   "rejectionReason": "string (if rejected)",
  #   "validationDetails": {
  #     "licensingCheck": "passed|failed",
  #     "appointmentCheck": "passed|failed", 
  #     "suitabilityCheck": "passed|failed",
  #     "policyRulesCheck": "passed|failed"
  #   },
  #   "responseTimestamp": "date-time",
  #   "additionalData": {}
  # }
